// Irodori Elementary 1 Lesson 5 — level hard. Bunpou tetap fokus Lesson 5; kanji dapat mencakup materi Irodori lain.
export const chapter5Hard = [
  {level:'hard',section:'Bunpou',q:"Pilih kalimat yang paling alami untuk 'Kota ini ramai dan praktis.'",options:['この町はにぎやかで、便利です。','この町はにぎやかくて、便利です。','この町はにぎやかだけど、便利です。','この町はにぎやかいで、便利です。'],answer:0,why:'にぎやか adalah ナ形容詞, jadi bentuk penghubungnya にぎやかで.'},
  {level:'hard',section:'Bunpou',q:"Pilih kalimat yang benar untuk 'Orangnya baik dan kota ini mudah ditinggali.'",options:['人がやさしくて、住みやすいです。','人がやさしいで、住みやすいです。','人がやさしだけど、住みやすいです。','人がやさしく、住みやすいだ。'],answer:0,why:'やさしい → やさしくて untuk menghubungkan dua keterangan.'},
  {level:'hard',section:'Bunpou',q:'Kalimat mana yang menampilkan KONTRAS, bukan sekadar penambahan?',options:['静かだけど、不便です。','静かで、便利です。','緑が多くて、静かです。','都会で、店が多いです。'],answer:0,why:'けど menghubungkan dua hal yang kontras.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: このスポーツセンターは古い（　）、安いです。',options:['けど','で','くて','ことが'],answer:0,why:'古い adalah イ形容詞, sehingga langsung diikuti けど.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: この辺りは静か（　）、ちょっと不便です。',options:['だけど','いけど','くて','ことが'],answer:0,why:'静か adalah ナ形容詞, sehingga bentuknya 静かだけど.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: ここは田舎（　）、のんびりしています。',options:['で','くて','いで','だけど'],answer:0,why:'名詞 untuk hubungan penambahan memakai ～で: 田舎で.'},
  {level:'hard',section:'Bunpou',q:'Pilih pasangan bentuk yang benar.',options:['便利 → 便利で / 安い → 安くて','便利 → 便利くて / 安い → 安いで','便利 → 便利だけど / 安い → 安で','便利 → 便利いで / 安い → 安だ'],answer:0,why:'ナ形容詞 memakai ～で, sedangkan イ形容詞 mengganti い menjadi くて.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: 日曜日は人が多い（　）、おもしろいです。',options:['けど','で','だ','ことが'],answer:0,why:'多い adalah イ形容詞 dan けど menyatakan kontras.'},
  {level:'hard',section:'Bunpou',q:"Kalimat yang benar untuk 'Walaupun agak jauh, ada bus.' adalah…",options:['ちょっと遠いけど、バスがあります。','ちょっと遠くてけど、バスがあります。','ちょっと遠いだけど、バスがあります。','ちょっと遠で、バスがあります。'],answer:0,why:'イ形容詞 + けど: 遠いけど.'},
  {level:'hard',section:'Bunpou',q:"Pilih kalimat yang benar untuk 'Di bukit ini kita bisa melihat laut dan kota.'",options:['この丘では、海と町を見ることができます。','この丘では、海と町を見てことができます。','この丘では、海と町を見ますことができます。','この丘では、海と町が見ることができます。'],answer:0,why:'V bentuk kamus + ことができます: 見ることができます.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: 一年中、いろいろな花を（　）ことができます。',options:['見る','見て','見ます','見た'],answer:0,why:'Sebelum ことができます dipakai bentuk kamus: 見る.'},
  {level:'hard',section:'Bunpou',q:'Lengkapi: やしが浜では、海で（　）ことができます。',options:['泳ぐ','泳いで','泳ぎます','泳いだ'],answer:0,why:'Bentuk kamus 泳ぐ dipakai sebelum ことができます.'},
  {level:'hard',section:'Susun Kalimat',q:"Urutan paling tepat untuk membentuk 'Bangunannya tua, tetapi murah dan bagus.' adalah…",options:['建物は古いけど、安くていいです。','建物は安いけど、古くていいです。','建物は古くて、安いけどいいです。','建物は古いで、安くだけどいいです。'],answer:0,why:'古いけど memberi kontras, sedangkan 安くて menghubungkan 安い dengan いい.'},
  {level:'hard',section:'Susun Kalimat',q:"Pilih kalimat yang paling tepat untuk mendeskripsikan tempat yang 'luas tetapi banyak orang'.",options:['ここは広いけど、人が多いです。','ここは広くて、人が多いけど。','ここは広いで、人が多いです。','ここは広だけど、人が多いです。'],answer:0,why:'広い adalah イ形容詞, jadi 広いけど.'},
  {level:'hard',section:'Susun Kalimat',q:"Pilih kalimat yang paling alami: 'Penghijauannya banyak, tenang, dan bagus.'",options:['緑が多くて、静かでいいです。','緑が多いで、静かくていいです。','緑が多くだけど、静かでいいです。','緑が多いけど、静かくていいです。'],answer:0,why:'多い → 多くて dan 静か → 静かで.'},
  {level:'hard',section:'Pemahaman',q:'「場所は不便だけど、きれいですよ。」 Apa hubungan dua bagian kalimat itu?',options:['penilaian negatif lalu positif','dua penilaian positif','sebab lalu akibat','kemampuan lalu hasil'],answer:0,why:'不便 bernilai negatif, sedangkan きれい bernilai positif; けど menandai kontras.'},
  {level:'hard',section:'Pemahaman',q:'「食堂や休憩所もあって、1日ゆっくりできます。」 Arti utamanya adalah…',options:['Ada kantin dan tempat istirahat sehingga bisa santai seharian.','Tidak ada kantin sehingga harus pulang cepat.','Hanya bisa masuk pada hari Minggu.','Tempatnya jauh dan tidak ada bus.'],answer:0,why:'Kalimat menyebut fasilitas dan kemungkinan untuk bersantai seharian.'},
  {level:'hard',section:'Pemahaman',q:'「ここから自転車で20分くらい。」 berarti…',options:['Sekitar 20 menit dari sini dengan sepeda.','Sekitar 20 menit berjalan kaki dari sini.','Naik bus nomor 20 dari sini.','Tempatnya buka selama 20 menit.'],answer:0,why:'自転車で menunjukkan alat transportasi, 20分くらい berarti kira-kira 20 menit.'},
  {level:'hard',section:'Pemahaman',q:'「ぜひ行ってみてください。」 Nuansa yang paling tepat adalah…',options:['Silakan coba pergi ke sana; sangat direkomendasikan.','Jangan pergi ke sana.','Saya tidak tahu tempatnya.','Pergilah hanya jika terpaksa.'],answer:0,why:'ぜひ menekankan rekomendasi, dan ～てみてください mengajak mencoba melakukan sesuatu.'},
  {level:'hard',section:'Pemahaman',q:'「この町には慣れましたか。」 menanyakan…',options:['apakah sudah terbiasa dengan kota ini','apakah kota ini terkenal','apakah sudah membeli rumah','apakah kota ini jauh'],answer:0,why:'慣れる berarti menjadi terbiasa.'},
  {level:'hard',section:'Kanji',q:'Cara baca 「駅」 adalah…',options:['えき','みち','ぎんこう','きたぐち'],answer:0,why:'駅 dibaca えき dan berarti stasiun.'},
  {level:'hard',section:'Kanji',q:'「道」 berarti…',options:['jalan','stasiun','bank','taman'],answer:0,why:'道（みち） berarti jalan.'},
  {level:'hard',section:'Kanji',q:'Cara baca 「銀行」 adalah…',options:['ぎんこう','ぎんぎょう','きんこう','ぎょうこう'],answer:0,why:'銀行 dibaca ぎんこう dan berarti bank.'},
  {level:'hard',section:'Kanji',q:'「公園」 berarti…',options:['taman','kantor pos','restoran','pantai'],answer:0,why:'公園（こうえん） berarti taman.'},
  {level:'hard',section:'Kanji',q:'Cara baca 「温泉」 adalah…',options:['おんせん','おんぜん','うんせん','あついみず'],answer:0,why:'温泉 dibaca おんせん dan berarti sumber air panas/onsen.'},
  {level:'hard',section:'Kanji',q:'「海」 berarti…',options:['laut','gunung','sungai','langit'],answer:0,why:'海（うみ） berarti laut.'},
  {level:'hard',section:'Kanji',q:'Cara baca 「花」 adalah…',options:['はな','はま','やま','かわ'],answer:0,why:'花 dibaca はな dan berarti bunga.'},
  {level:'hard',section:'Kanji',q:'「毎日」 berarti…',options:['setiap hari','setiap minggu','kemarin','besok'],answer:0,why:'毎日（まいにち） berarti setiap hari.'},
  {level:'hard',section:'Kanji',q:'Cara baca 「仕事」 adalah…',options:['しごと','しこと','じごと','しごう'],answer:0,why:'仕事 dibaca しごと dan berarti pekerjaan.'},
  {level:'hard',section:'Kanji',q:'「時間」 berarti…',options:['waktu','tempat','orang','kendaraan'],answer:0,why:'時間（じかん） berarti waktu.'}
]