// Irodori Elementary 1 Lesson 5 — latihan orisinal berbasis kosakata, bunpou, dan kanji bab.
export const chapter5Medium = [
  {level:'medium',section:'Arti',q:'「便利（べんり）」 berarti…',options:['nyaman/praktis','sepi','jauh','murah'],answer:0,why:'便利 berarti praktis atau nyaman untuk digunakan.'},
  {level:'medium',section:'Arti',q:'「不便（ふべん）」 berarti…',options:['tidak praktis/tidak nyaman','ramai','indah','terkenal'],answer:0,why:'不便 adalah kebalikan dari 便利, yaitu tidak praktis atau tidak nyaman.'},
  {level:'medium',section:'Arti',q:'「にぎやか」 paling tepat berarti…',options:['ramai/meriah','tenang','sempit','dingin'],answer:0,why:'にぎやか adalah kata sifat-na yang berarti ramai atau meriah.'},
  {level:'medium',section:'Arti',q:'「静か（しずか）」 berarti…',options:['tenang','ramai','dekat','baru'],answer:0,why:'静か berarti tenang atau sunyi.'},
  {level:'medium',section:'Arti',q:'「緑が多い」 berarti…',options:['banyak penghijauan','banyak toko','sedikit bus','pemandangannya indah'],answer:0,why:'緑 = hijau/penghijauan dan 多い = banyak.'},
  {level:'medium',section:'Arti',q:'「景色（けしき）」 berarti…',options:['pemandangan','bangunan','rest area','pantai'],answer:0,why:'景色 berarti pemandangan.'},
  {level:'medium',section:'Arti',q:'「田舎（いなか）」 berarti…',options:['daerah pedesaan','kota besar','pusat belanja','stasiun'],answer:0,why:'田舎 berarti desa atau daerah pedesaan.'},
  {level:'medium',section:'Arti',q:'「都会（とかい）」 berarti…',options:['daerah perkotaan','bukit','pedesaan','pantai berpasir'],answer:0,why:'都会 berarti kota atau daerah perkotaan.'},
  {level:'medium',section:'Arti',q:'「住みやすい」 berarti…',options:['nyaman/mudah untuk ditinggali','sulit dicapai','mudah dimakan','bisa berenang'],answer:0,why:'住みやすい berarti mudah atau nyaman untuk ditinggali.'},
  {level:'medium',section:'Arti',q:'「おすすめ」 berarti…',options:['rekomendasi','larangan','jadwal','arah'],answer:0,why:'おすすめ berarti sesuatu yang direkomendasikan.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: この町は、とてもにぎやか（　）、便利です。',options:['で','くて','だけど','ことが'],answer:0,why:'にぎやか adalah ナ形容詞, sehingga untuk menyambungkan sifat dipakai ～で.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: 人がやさし（　）、住みやすいです。',options:['くて','で','だけど','だ'],answer:0,why:'やさしい adalah イ形容詞. Saat menghubungkan dua sifat, い berubah menjadi くて.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: 緑が多（　）、静かでいいですね。',options:['くて','で','だけど','いで'],answer:0,why:'多い → 多くて ketika dihubungkan dengan kalimat berikutnya.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: バスが少な（　）、ちょっと不便です。',options:['くて','で','だけど','いけど'],answer:0,why:'少ない → 少なくて untuk menyambungkan sebab/keterangan dengan penilaian berikutnya.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: 建物は古い（　）、安くていいです。',options:['けど','で','くて','ことが'],answer:0,why:'イ形容詞 + けど dipakai untuk mengontraskan dua penilaian.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: 場所は不便だ（　）、きれいですよ。',options:['けど','くて','で','ことが'],answer:0,why:'ナ形容詞 sebelum けど memakai bentuk ～だけど: 不便だけど.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: ここからちょっと遠い（　）、バスがあります。',options:['けど','で','くて','だ'],answer:0,why:'遠い adalah イ形容詞, sehingga bentuk kontrasnya 遠いけど.'},
  {level:'medium',section:'Bunpou',q:'Kalimat yang benar adalah…',options:['都会だけど、緑が多いです。','都会でけど、緑が多いです。','都会くて、緑が多いです。','都会いけど、緑が多いです。'],answer:0,why:'Noun + けど memakai だ: 都会だけど.'},
  {level:'medium',section:'Bunpou',q:'Lengkapi: この店では、地元の料理を食べる（　）。',options:['ことができます','でできます','くてできます','だけどできます'],answer:0,why:'Kemungkinan melakukan aksi dinyatakan dengan V bentuk kamus + ことができます.'},
  {level:'medium',section:'Bunpou',q:"Bentuk yang benar untuk 'bisa berenang' adalah…",options:['泳ぐことができます','泳いでことができます','泳ぎことができます','泳ぐでできます'],answer:0,why:'Gunakan bentuk kamus 泳ぐ + ことができます.'},
  {level:'medium',section:'Kanji',q:'Arti kanji 「町」 adalah…',options:['kota/daerah','toko','jalan','gunung'],answer:0,why:'町（まち） berarti kota atau daerah tempat tinggal.'},
  {level:'medium',section:'Kanji',q:'Cara baca 「店」 adalah…',options:['みせ','まち','とおい','しずか'],answer:0,why:'店 dibaca みせ dan berarti toko.'},
  {level:'medium',section:'Kanji',q:'「食堂」 dibaca…',options:['しょくどう','しょくみせ','たべどう','しょどう'],answer:0,why:'食堂 dibaca しょくどう dan berarti kantin/ruang makan.'},
  {level:'medium',section:'Kanji',q:'「有名」 berarti…',options:['terkenal','tenang','jauh','ramai'],answer:0,why:'有名（ゆうめい） berarti terkenal.'},
  {level:'medium',section:'Kanji',q:'Cara baca 「多い」 adalah…',options:['おおい','すくない','とおい','おもい'],answer:0,why:'多い dibaca おおい dan berarti banyak.'},
  {level:'medium',section:'Kanji',q:'「少ない」 berarti…',options:['sedikit','banyak','murah','luas'],answer:0,why:'少ない（すくない） berarti sedikit/tidak banyak.'},
  {level:'medium',section:'Kanji',q:'Cara baca 「便利」 adalah…',options:['べんり','ふべん','ゆうめい','しずか'],answer:0,why:'便利 dibaca べんり.'},
  {level:'medium',section:'Kanji',q:'「不便」 dibaca…',options:['ふべん','べんり','ふゆう','ぶべん'],answer:0,why:'不便 dibaca ふべん dan berarti tidak praktis.'},
  {level:'medium',section:'Kanji',q:'Cara baca 「遠い」 adalah…',options:['とおい','ちかい','おおい','ふるい'],answer:0,why:'遠い dibaca とおい dan berarti jauh.'},
  {level:'medium',section:'Kanji',q:'「静か」 berarti…',options:['tenang','ramai','luas','tua'],answer:0,why:'静か（しずか） berarti tenang.'}
]
