// Latihan JLPT N4 — kanji N4 dan bunpou tingkat N4/Irodori lintas bab.
export const jlptN4 = [
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 日本へ行った（　）があります。',options:['こと','もの','ところ','ため'],answer:0,why:'V-たことがあります menyatakan pengalaman pernah melakukan sesuatu.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 音楽を聞き（　）、勉強します。',options:['ながら','まで','しか','ので'],answer:0,why:'Vます-stem + ながら menyatakan dua kegiatan yang dilakukan bersamaan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 明日は早いですから、早く寝なければ（　）。',options:['なりません','います','できます','ください'],answer:0,why:'～なければなりません menyatakan keharusan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'「ここで写真を撮ってもいいです。」 berarti…',options:['Boleh mengambil foto di sini.','Dilarang mengambil foto di sini.','Harus mengambil foto di sini.','Tidak bisa mengambil foto di sini.'],answer:0,why:'～てもいいです menyatakan izin.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: ここでたばこを吸っては（　）。',options:['いけません','できます','ありません','なりたい'],answer:0,why:'～てはいけません menyatakan larangan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: このかばんは重（　）すぎます。',options:['すぎ','い','くて','さ'],answer:0,why:'Untuk イ形容詞, buang い lalu tambahkan ～すぎる: 重い → 重すぎる.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 来年、日本へ留学する（　）です。',options:['つもり','ながら','ほう','しか'],answer:0,why:'V辞書形 + つもりです menyatakan niat/rencana.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 会議は3時に始まる（　）です。',options:['予定','経験','必要','意味'],answer:0,why:'～予定です menyatakan jadwal atau rencana yang sudah ditetapkan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 雨が降っている（　）、出かけません。',options:['ので','ながら','しか','まで'],answer:0,why:'～ので menyatakan alasan dengan nuansa lebih lembut daripada から.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'A: どうして遅れたんですか。 B: 電車が遅れた（　）。',options:['んです','そうです','つもりです','ことです'],answer:0,why:'～んです dipakai untuk memberi penjelasan atau latar belakang.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'「この漢字の読み方を教えてください。」 Arti 「読み方」 adalah…',options:['cara membaca','cara menulis','waktu membaca','tempat membaca'],answer:0,why:'Vます-stem + 方 berarti cara melakukan sesuatu.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: この靴は歩き（　）です。',options:['やすい','にくい','そう','たい'],answer:0,why:'Vます-stem + やすい berarti mudah untuk dilakukan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: この字は小さくて、読み（　）です。',options:['にくい','やすい','たい','そう'],answer:0,why:'Vます-stem + にくい berarti sulit untuk dilakukan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 寝る（　）に、歯をみがきます。',options:['前','後','中','間'],answer:0,why:'V辞書形 + 前に berarti sebelum melakukan sesuatu.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: ご飯を食べた（　）で、薬を飲みます。',options:['あと','まえ','あいだ','まで'],answer:0,why:'V-た + あとで berarti setelah melakukan sesuatu.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 日曜日は掃除したり、買い物に行っ（　）します。',options:['たり','て','たら','ても'],answer:0,why:'～たり～たりします memberi beberapa contoh kegiatan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'空が暗いです。雨が降り（　）です。',options:['そう','たい','やすい','ながら'],answer:0,why:'Vます-stem + そうです menyatakan sesuatu yang tampaknya akan terjadi.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 毎日練習して、日本語が話せる（　）なりました。',options:['ように','ために','そうに','ことに'],answer:0,why:'～ようになりました menyatakan perubahan kemampuan atau kebiasaan.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:'Lengkapi: 健康のために、毎朝歩く（　）しました。',options:['ことに','ように','そうに','ために'],answer:0,why:'～ことにしました menyatakan keputusan yang dibuat sendiri.'},
  {level:'jlpt',section:'JLPT N4 Bunpou',q:"Pilih kalimat yang benar untuk 'Saya pikir kota ini nyaman.'",options:['この町は便利だと思います。','この町は便利と思います。','この町は便利でと思います。','この町は便利にと思います。'],answer:0,why:'Sebelum と思います, ナ形容詞 memakai bentuk biasa dengan だ: 便利だと思います.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'Cara baca 「旅行」 adalah…',options:['りょこう','りょうこう','りょこ','りょごう'],answer:0,why:'旅行 dibaca りょこう dan berarti perjalanan/travel.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'「病院」 berarti…',options:['rumah sakit','stasiun','balai kota','sekolah'],answer:0,why:'病院（びょういん） berarti rumah sakit.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'Cara baca 「写真」 adalah…',options:['しゃしん','しゃじん','さしん','しゃせん'],answer:0,why:'写真 dibaca しゃしん dan berarti foto.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'「帰る」 berarti…',options:['pulang','pergi','bertemu','berdiri'],answer:0,why:'帰る（かえる） berarti pulang/kembali.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'Cara baca 「運転」 adalah…',options:['うんてん','うんでん','うてん','うんせん'],answer:0,why:'運転 dibaca うんてん dan berarti mengemudi.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'「住所」 berarti…',options:['alamat','tempat kerja','jadwal','tujuan'],answer:0,why:'住所（じゅうしょ） berarti alamat.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'Cara baca 「始まる」 adalah…',options:['はじまる','おわる','はしまる','はじめる'],answer:0,why:'始まる dibaca はじまる dan berarti mulai (intransitif).'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'「終わる」 berarti…',options:['berakhir/selesai','dimulai','berubah','berjalan'],answer:0,why:'終わる（おわる） berarti selesai atau berakhir.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'Cara baca 「春」 adalah…',options:['はる','なつ','あき','ふゆ'],answer:0,why:'春 dibaca はる dan berarti musim semi.'},
  {level:'jlpt',section:'JLPT N4 Kanji',q:'「秋」 berarti…',options:['musim gugur','musim panas','musim semi','musim dingin'],answer:0,why:'秋（あき） berarti musim gugur.'}
]